/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AuthenticationApi,
  CompanyApi,
  ManagementApi,
  PayrollApi,
  WebhooksApi,
  WorkerApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { PaychexCustom } from "./client-custom";

export class Paychex extends PaychexCustom {
  readonly authentication: AuthenticationApi;
  readonly company: CompanyApi;
  readonly management: ManagementApi;
  readonly payroll: PayrollApi;
  readonly webhooks: WebhooksApi;
  readonly worker: WorkerApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.authentication = new AuthenticationApi(configuration);
    this.company = new CompanyApi(configuration);
    this.management = new ManagementApi(configuration);
    this.payroll = new PayrollApi(configuration);
    this.webhooks = new WebhooksApi(configuration);
    this.worker = new WorkerApi(configuration);
  }

}
