/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AcknowledgementResource
 */
export interface AcknowledgementResource {
    /**
     * 
     * @type {string}
     * @memberof AcknowledgementResource
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof AcknowledgementResource
     */
    'status'?: string;
}

