/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Authentication Response
 * @export
 * @interface Authentication
 */
export interface Authentication {
    /**
     * The token which will be used for making future calls.
     * @type {string}
     * @memberof Authentication
     */
    'access_token'?: string;
    /**
     * Number of seconds remaining before the token expires.
     * @type {string}
     * @memberof Authentication
     */
    'expires_in'?: string;
    /**
     * This will always return \'oob\' (out of band) based on OAuth configuration.
     * @type {string}
     * @memberof Authentication
     */
    'scope'?: string;
    /**
     * This will always return \'Bearer\' based on OAuth configuration.
     * @type {string}
     * @memberof Authentication
     */
    'token_type'?: string;
}

