/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AuthenticationCreateBearerTokenRequest
 */
export interface AuthenticationCreateBearerTokenRequest {
    /**
     * Send \"client_credentials\".
     * @type {string}
     * @memberof AuthenticationCreateBearerTokenRequest
     */
    'grant_type': string;
    /**
     * The applications API key.
     * @type {string}
     * @memberof AuthenticationCreateBearerTokenRequest
     */
    'client_id': string;
    /**
     * The applications corresponding secret.
     * @type {string}
     * @memberof AuthenticationCreateBearerTokenRequest
     */
    'client_secret': string;
}

