/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CalcMethod
 */
export interface CalcMethod {
    /**
     * 
     * @type {number}
     * @memberof CalcMethod
     */
    'ccmId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcMethod
     */
    'defaultTypeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CalcMethod
     */
    'defaultType'?: string;
    /**
     * 
     * @type {number}
     * @memberof CalcMethod
     */
    'calcTypeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CalcMethod
     */
    'calculationType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CalcMethod
     */
    'calcType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CalcMethod
     */
    'calcAdjType'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CalcMethod
     */
    'isIncludeMemoHours'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CalcMethod
     */
    'isTieredByPct'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CalcMethod
     */
    'isMatchCalcAsPct'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CalcMethod
     */
    'calcAdjTypeId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcMethod
     */
    'payRateOvrdTypeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CalcMethod
     */
    'payRateOvrdType'?: string;
}

