/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The state representation of CalculationBase
 * @export
 * @interface CalculationBase
 */
export interface CalculationBase {
    /**
     * The unique ID associated with Calculation Base
     * @type {string}
     * @memberof CalculationBase
     */
    'calculationBaseId'?: string;
    /**
     * Name of CalculationBase
     * @type {string}
     * @memberof CalculationBase
     */
    'calculationBaseName'?: string;
}

