/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { PayComponentResource } from './pay-component-resource';

/**
 * The state representation of Labor Assignments within a company.
 * @export
 * @interface CheckResource
 */
export interface CheckResource {
    /**
     * The id assigned to the worker.
     * @type {string}
     * @memberof CheckResource
     */
    'workerId'?: string;
    /**
     * The id of a single check that a workers has.
     * @type {string}
     * @memberof CheckResource
     */
    'paycheckId'?: string;
    /**
     * The id for the unprocessed payperiod. 
     * @type {string}
     * @memberof CheckResource
     */
    'payPeriodId'?: string;
    /**
     * Id that you define which is used for error handling/responses. This is not required when sending a single check.
     * @type {string}
     * @memberof CheckResource
     */
    'checkCorrelationId'?: string;
    /**
     * This is used optionally for blocking the auto distribution of the earnings on the workers if they are setup for auto distribution.
     * @type {boolean}
     * @memberof CheckResource
     */
    'blockAutoDistribution'?: boolean;
    /**
     * The earnings to apply to the check.Each earning needs to define as one of the following:1 .payHours: Will use the default hourly rate defined on the worker to apply the hours against. 2. payHours and payRate: Will allow you to define the monetary rate that the hours will be applied against. 3. payHours and payRateId: Will allow you to define which workers predefined pay rate the hours will be applied against. 4. payUnits: Will use the default hourly rate defined on the worker to apply the units against. 5. payUnits and payRate: Will allow you to define the monetary rate that the units will be applied against. 6. payUnits and payRateId: Will allow you to define which workers predefined pay rate the units will be applied against. 7. payAmount: Will allow you to define straight monetary amount.
     * @type {Array<PayComponentResource>}
     * @memberof CheckResource
     */
    'earnings'?: Array<PayComponentResource>;
    /**
     * Deduction pay components on the check.
     * @type {Array<PayComponentResource>}
     * @memberof CheckResource
     */
    'deductions'?: Array<PayComponentResource>;
    /**
     * The check date 
     * @type {string}
     * @memberof CheckResource
     */
    'checkDate'?: string;
    /**
     * Informational pay components on the check.
     * @type {Array<PayComponentResource>}
     * @memberof CheckResource
     */
    'informational'?: Array<PayComponentResource>;
    /**
     * Tax pay components on the check.
     * @type {Array<PayComponentResource>}
     * @memberof CheckResource
     */
    'taxes'?: Array<PayComponentResource>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof CheckResource
     */
    'links'?: Array<Link>;
}

