/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { PayComponentResource2 } from './pay-component-resource2';

/**
 * 
 * @export
 * @interface CheckResource2
 */
export interface CheckResource2 {
    /**
     * The worker Id
     * @type {string}
     * @memberof CheckResource2
     */
    'workerId'?: string;
    /**
     * The paycheck Id
     * @type {string}
     * @memberof CheckResource2
     */
    'paycheckId'?: string;
    /**
     * The id of payperiod. 
     * @type {string}
     * @memberof CheckResource2
     */
    'payPeriodId'?: string;
    /**
     * Id that you define which is used for error handling/responses. This is not required when sending a single check.
     * @type {string}
     * @memberof CheckResource2
     */
    'checkCorrelationId'?: string;
    /**
     * This is used optionally for blocking the auto distribution of the earnings on the workers if they are setup for auto distribution.
     * @type {boolean}
     * @memberof CheckResource2
     */
    'blockAutoDistribution'?: CheckResource2BlockAutoDistributionEnum;
    /**
     * The earnings to apply to the check.Each earning needs to define as one of the following:1 .payHours: Will use the default hourly rate defined on the worker to apply the hours against. 2. payHours and payRate: Will allow you to define the monetary rate that the hours will be applied against. 3. payHours and payRateId: Will allow you to define which workers predefined pay rate the hours will be applied against. 4. payUnits: Will use the default hourly rate defined on the worker to apply the units against. 5. payUnits and payRate: Will allow you to define the monetary rate that the units will be applied against. 6. payUnits and payRateId: Will allow you to define which workers predefined pay rate the units will be applied against. 7. payAmount: Will allow you to define straight monetary amount.
     * @type {Array<PayComponentResource2>}
     * @memberof CheckResource2
     */
    'earnings'?: Array<PayComponentResource2>;
    /**
     * Deduction pay components on the check.
     * @type {Array<PayComponentResource2>}
     * @memberof CheckResource2
     */
    'deductions'?: Array<PayComponentResource2>;
    /**
     * Informational pay components on the check.
     * @type {Array<PayComponentResource2>}
     * @memberof CheckResource2
     */
    'informational'?: Array<PayComponentResource2>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof CheckResource2
     */
    'links'?: Array<Link>;
}

type CheckResource2BlockAutoDistributionEnum = true | false


