/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Client } from './client';

/**
 * 
 * @export
 * @interface ClientVersion
 */
export interface ClientVersion {
    /**
     * 
     * @type {number}
     * @memberof ClientVersion
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'taxPayerIdentificationNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'tinLastFour'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'tinType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'tinValidStatusCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedCity'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedCountryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'versionStatusCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'beginEffectiveDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'endEffectiveDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedBuildingNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedSteetName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedUnitName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedPOBox'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedStateProvince'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedStateProvinceF'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'normalizedPostalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'tinVersionStatusCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'statusDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'superceededBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'modifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'modifiedByApplicationName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'modifiedByApplicationSubProcessName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'modifiedByUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVersion
     */
    'modifiedReason'?: string;
    /**
     * 
     * @type {Client}
     * @memberof ClientVersion
     */
    'client'?: Client;
}

