/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ClientName } from './client-name';

/**
 * 
 * @export
 * @interface ClientNameVersion
 */
export interface ClientNameVersion {
    /**
     * 
     * @type {number}
     * @memberof ClientNameVersion
     */
    'cnvId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientNameVersion
     */
    'cnvCltNm'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientNameVersion
     */
    'cnvVerStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientNameVersion
     */
    'cnvValStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientNameVersion
     */
    'cnvBegnEffDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientNameVersion
     */
    'cnvEndEffDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientNameVersion
     */
    'cnvModDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientNameVersion
     */
    'cnvModByAppNm'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientNameVersion
     */
    'cnvModByAppUsrNm'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientNameVersion
     */
    'cnvModByAppSubNm'?: string;
    /**
     * 
     * @type {ClientName}
     * @memberof ClientNameVersion
     */
    'cltNmByCnId'?: ClientName;
}

