/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CalcMethod } from './calc-method';
import { ClientPayComponentFrequency } from './client-pay-component-frequency';
import { ClientPayComponentOptions } from './client-pay-component-options';
import { ClientPayComponentWorkerTypes } from './client-pay-component-worker-types';
import { PayComponent } from './pay-component';

/**
 * 
 * @export
 * @interface ClientPayComponentResponse
 */
export interface ClientPayComponentResponse {
    /**
     * 
     * @type {PayComponent}
     * @memberof ClientPayComponentResponse
     */
    'payComponent'?: PayComponent;
    /**
     * 
     * @type {ClientPayComponentFrequency}
     * @memberof ClientPayComponentResponse
     */
    'frequencyData'?: ClientPayComponentFrequency;
    /**
     * 
     * @type {Array<CalcMethod>}
     * @memberof ClientPayComponentResponse
     */
    'calcMethods'?: Array<CalcMethod>;
    /**
     * 
     * @type {Array<ClientPayComponentWorkerTypes>}
     * @memberof ClientPayComponentResponse
     */
    'workerTypes'?: Array<ClientPayComponentWorkerTypes>;
    /**
     * 
     * @type {Array<ClientPayComponentOptions>}
     * @memberof ClientPayComponentResponse
     */
    'options'?: Array<ClientPayComponentOptions>;
}

