/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ClientAccountRegistration } from './client-account-registration';

/**
 * 
 * @export
 * @interface ClientAccount
 */
export interface ClientAccount {
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'externalCAID'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'externalId'?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientAccount
     */
    'lockVersion'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'applicationName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'assignedName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'createdDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'createdByApplicationName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'createdByUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'routeAttributeName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'createdByApplicationSubProcessName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'routeAttributeValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'modifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'modifiedByApplicationName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'modifiedByApplicationSubProcessName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'modifiedByUserId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClientAccount
     */
    'parentIndicator'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'displayName'?: string;
    /**
     * 
     * @type {Array<ClientAccountRegistration>}
     * @memberof ClientAccount
     */
    'clientAccountRegistrations'?: Array<ClientAccountRegistration>;
    /**
     * 
     * @type {string}
     * @memberof ClientAccount
     */
    'caid'?: string;
}

