/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * 
 * @export
 * @interface CommunicationResource1
 */
export interface CommunicationResource1 {
    /**
     * The ID for the workers specific communication item.
     * @type {string}
     * @memberof CommunicationResource1
     */
    'communicationId'?: string;
    /**
     * A set of communication types classifying an instruction that the customer, requester, or subject must comply with in order for the screening to go forward. NOTE: PHONE and EMAIL type supports BUSINESS and PERSONAL usage type only.MOBILE_PHONE, FAX and PAGER supports BUSINESS usage type only.This data field cannot be PATCHED.
     * @type {string}
     * @memberof CommunicationResource1
     */
    'type'?: CommunicationResource1TypeEnum;
    /**
     * A code classifying a designated use associated with a contact method. For example, whether a telephone or email address is one for business communications or one primarily for personal use.This data field cannot be PATCHED.
     * @type {string}
     * @memberof CommunicationResource1
     */
    'usageType'?: CommunicationResource1UsageTypeEnum;
    /**
     * The country dialing code for a communication number
     * @type {string}
     * @memberof CommunicationResource1
     */
    'dialCountry'?: string;
    /**
     * The area dialing code for a communication number
     * @type {string}
     * @memberof CommunicationResource1
     */
    'dialArea'?: string;
    /**
     * The communication number, not including country dialing or area dialing codes
     * @type {string}
     * @memberof CommunicationResource1
     */
    'dialNumber'?: string;
    /**
     * The extension of the associated communication number
     * @type {string}
     * @memberof CommunicationResource1
     */
    'dialExtension'?: string;
    /**
     * The mailto address as specified in RFC2368
     * @type {string}
     * @memberof CommunicationResource1
     */
    'uri'?: string;
    /**
     * The street address line one
     * @type {string}
     * @memberof CommunicationResource1
     */
    'streetLineOne'?: string;
    /**
     * The street address line two
     * @type {string}
     * @memberof CommunicationResource1
     */
    'streetLineTwo'?: string;
    /**
     * The postal office box. This data field cannot be PATCHED
     * @type {string}
     * @memberof CommunicationResource1
     */
    'postOfficeBox'?: string;
    /**
     * The city name
     * @type {string}
     * @memberof CommunicationResource1
     */
    'city'?: string;
    /**
     * The zip-code
     * @type {string}
     * @memberof CommunicationResource1
     */
    'postalCode'?: string;
    /**
     * The zip-code extension
     * @type {string}
     * @memberof CommunicationResource1
     */
    'postalCodeExtension'?: string;
    /**
     * The state code (ISO 3166 subdivision code). This data field cannot be PATCHED for ACTIVE worker
     * @type {string}
     * @memberof CommunicationResource1
     */
    'countrySubdivisionCode'?: string;
    /**
     * The country code (ISO 3166 alpha-2)
     * @type {string}
     * @memberof CommunicationResource1
     */
    'countryCode'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof CommunicationResource1
     */
    'links'?: Array<Link>;
}

type CommunicationResource1TypeEnum = 'STREET_ADDRESS' | 'PO_BOX_ADDRESS' | 'PHONE' | 'MOBILE_PHONE' | 'FAX' | 'EMAIL' | 'PAGER'
type CommunicationResource1UsageTypeEnum = 'PERSONAL' | 'BUSINESS' | 'HOME' | 'WORK' | 'LOCATION_STREET_ADDRESS' | 'MAILING_ADDRESS'


