/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { RelationTypeResource } from './relation-type-resource';

/**
 * 
 * @export
 * @interface ContactTypeResource
 */
export interface ContactTypeResource {
    /**
     * 
     * @type {string}
     * @memberof ContactTypeResource
     */
    'contactTypeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactTypeResource
     */
    'contactTypeName'?: string;
    /**
     * 
     * @type {Array<RelationTypeResource>}
     * @memberof ContactTypeResource
     */
    'relationshipTypes'?: Array<RelationTypeResource>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof ContactTypeResource
     */
    'links'?: Array<Link>;
}

