/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The type of this worker contact. Required for POST contacts.
 * @export
 * @interface ContactTypeResource1
 */
export interface ContactTypeResource1 {
    /**
     * The ID for specific type of contact. Required for POST contacts.
     * @type {string}
     * @memberof ContactTypeResource1
     */
    'contactTypeId'?: string;
    /**
     * Enum:  \"EMERGENCY_CONTACT\"  The name for specific type of contact.
     * @type {string}
     * @memberof ContactTypeResource1
     */
    'contactTypeName'?: string;
}

