/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldsDropdownResource } from './custom-fields-dropdown-resource';
import { Link } from './link';

/**
 * 
 * @export
 * @interface CustomFieldsResource
 */
export interface CustomFieldsResource {
    /**
     * The unique identifier that is autogenerated when a custom field is created
     * @type {string}
     * @memberof CustomFieldsResource
     */
    'customFieldId'?: string;
    /**
     * The name of the custom field
     * @type {string}
     * @memberof CustomFieldsResource
     */
    'customFieldName'?: string;
    /**
     * The unique identifier that is autogenerated when creating a category
     * @type {string}
     * @memberof CustomFieldsResource
     */
    'categoryId'?: string;
    /**
     * Where to indicate if the custom field is required on the worker where true = required and false = not required
     * @type {boolean}
     * @memberof CustomFieldsResource
     */
    'required'?: boolean;
    /**
     * Where to indicate if the custom field is required on the worker\'s pay stub, where true = required and false = not required
     * @type {boolean}
     * @memberof CustomFieldsResource
     */
    'checkStub'?: boolean;
    /**
     * Where to indicate if the custom field is able to be edited by the employee, where true = required and false = not required
     * @type {boolean}
     * @memberof CustomFieldsResource
     */
    'employeeEditable'?: boolean;
    /**
     * The type of field the custom field is.
     * @type {string}
     * @memberof CustomFieldsResource
     */
    'type'?: CustomFieldsResourceTypeEnum;
    /**
     * The value for BOOLEAN type (true / false)
     * @type {boolean}
     * @memberof CustomFieldsResource
     */
    'booleanValue'?: boolean;
    /**
     * 
     * @type {Array<Link>}
     * @memberof CustomFieldsResource
     */
    'links'?: Array<Link>;
    /**
     * The value for DATE type , example : 2012-02-01T05:00:00Z
     * @type {string}
     * @memberof CustomFieldsResource
     */
    'dateValue'?: string;
    /**
     * The value for TEXT type (any text, alphanumeric, special characters allowed)
     * @type {string}
     * @memberof CustomFieldsResource
     */
    'textValue'?: string;
    /**
     * The maximum allowed value for textValue
     * @type {number}
     * @memberof CustomFieldsResource
     */
    'maxTextLength'?: number;
    /**
     * Numeric data type can have three formats namely - whole number, second decimal place and fourth decimal place, example: 12 , 12.34 or 12.3456
     * @type {number}
     * @memberof CustomFieldsResource
     */
    'numericValue'?: number;
    /**
     * 
     * @type {Array<CustomFieldsDropdownResource>}
     * @memberof CustomFieldsResource
     */
    'dropdown'?: Array<CustomFieldsDropdownResource>;
}

type CustomFieldsResourceTypeEnum = 'DROPDOWN' | 'TEXT' | 'BOOLEAN' | 'DATE' | 'NUMERIC, NUMERIC__0_00_ OR NUMERIC__0_0000_'


