/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomFieldsDropdownResource
 */
export interface CustomFieldsDropdownResource {
    /**
     * The unique identifier that is autogenerated when dropdown list is created
     * @type {string}
     * @memberof CustomFieldsDropdownResource
     */
    'dropdownId'?: string;
    /**
     * The value for dropdown list
     * @type {string}
     * @memberof CustomFieldsDropdownResource
     */
    'dropdownValue'?: string;
    /**
     * The default value for dropdown list
     * @type {boolean}
     * @memberof CustomFieldsDropdownResource
     */
    'dropdownDefault'?: boolean;
}

