/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DeepUrlResponseResource
 */
export interface DeepUrlResponseResource {
    /**
     * The deeplink URL that redirects a Flex client Admin to the Flex integrated apps drawer for their approval or denial of the partner integration
     * @type {string}
     * @memberof DeepUrlResponseResource
     */
    'approvalLink'?: string;
}

