/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * Worker direct deposit
 * @export
 * @interface DirectDepositResource
 */
export interface DirectDepositResource {
    /**
     * The ID for the direct deposit item.
     * @type {string}
     * @memberof DirectDepositResource
     */
    'directDepositId'?: string;
    /**
     * The date that this direct deposit will be applied to future pay periods. This data field cannot be PATCHED.
     * @type {string}
     * @memberof DirectDepositResource
     */
    'startDate'?: string;
    /**
     * A type of payment for the direct deposit.
     * @type {string}
     * @memberof DirectDepositResource
     */
    'paymentType'?: DirectDepositResourcePaymentTypeEnum;
    /**
     * Financial institutions account type. This data field cannot be PATCHED.
     * @type {string}
     * @memberof DirectDepositResource
     */
    'accountType'?: DirectDepositResourceAccountTypeEnum;
    /**
     * The amount to be applied to this direct deposit.
     * @type {number}
     * @memberof DirectDepositResource
     */
    'value'?: number;
    /**
     * The financial institutions routing number.This data field cannot be PATCHED.
     * @type {string}
     * @memberof DirectDepositResource
     */
    'routingNumber'?: string;
    /**
     * The financial institutions account number.This data field cannot be PATCHED.
     * @type {string}
     * @memberof DirectDepositResource
     */
    'accountNumber'?: string;
    /**
     * The priority order for which the direct deposits will be performed in. When a new direct deposit is added the priority will be assigned. The priority can be modified only by swapping with a different direct deposit using the bulk PATCH. A paymentType of REMAINDER will show a priority of 99 and can\'t be modified.This data field cannot be PATCHED.
     * @type {string}
     * @memberof DirectDepositResource
     */
    'priority'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof DirectDepositResource
     */
    'links'?: Array<Link>;
}

type DirectDepositResourcePaymentTypeEnum = 'FLAT_DOLLAR_AMOUNT' | 'PERCENTAGE' | 'REMAINDER'
type DirectDepositResourceAccountTypeEnum = 'CHECKING' | 'SAVINGS' | 'CREDIT_CARD'


