/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { WorkerErrorResource } from './worker-error-resource';

/**
 * 
 * @export
 * @interface EmailResource1
 */
export interface EmailResource1 {
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'primaryEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'secondaryEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'connectionName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'displayId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'legalName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'notificationType'?: EmailResource1NotificationTypeEnum;
    /**
     * 
     * @type {Array<WorkerErrorResource>}
     * @memberof EmailResource1
     */
    'workerErrors'?: Array<WorkerErrorResource>;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'payPeriod'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'partnerLocationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'sourceJobName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'bcc'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'employeeFirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'employeeLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailResource1
     */
    'linkToSurvey'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof EmailResource1
     */
    'links'?: Array<Link>;
}

type EmailResource1NotificationTypeEnum = 'CONNECTION_ERROR' | 'DATA_ERROR' | 'WORKER_CHECK_ERROR' | 'MULTI_ID_SPI_REJECT' | 'EMPLOYEE_OVERTIME_NOTIFICATION' | 'COMPANY_PAY_PERIOD_ERROR' | 'PAYROLL_CONFIRMATION' | 'COMPANY_JOBCODE' | 'OFFBOARDING_SURVEY' | 'OFFBOARDING_ERROR' | 'WORKER_PUNCH_OR_ADJUSTMENT_ERROR' | 'WORKER_SCHEDULE_ERROR'


