/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EntityCommunicationResource } from './entity-communication-resource';

/**
 * The organization associated with this relationship. The relationship must have either a person or entity.
 * @export
 * @interface EntityResource
 */
export interface EntityResource {
    /**
     * The ID for this contact.
     * @type {string}
     * @memberof EntityResource
     */
    'entityId'?: string;
    /**
     * The entity name. Required for POST contacts.
     * @type {string}
     * @memberof EntityResource
     */
    'entityName'?: string;
    /**
     * 
     * @type {EntityCommunicationResource}
     * @memberof EntityResource
     */
    'communication'?: EntityCommunicationResource;
}

