/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * These are sub intervals that are used for occurrences that are larger in duration that allow you to define when to apply the pay component.
 * @export
 * @interface FrequencyIntervalsResource
 */
export interface FrequencyIntervalsResource {
    /**
     * Interval 1 
     * @type {string}
     * @memberof FrequencyIntervalsResource
     */
    'interval1'?: string;
    /**
     * Interval 2
     * @type {string}
     * @memberof FrequencyIntervalsResource
     */
    'interval2'?: string;
}

