/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { PayComponentFrequencyTypeResource } from './pay-component-frequency-type-resource';

/**
 * The state representation of generic pay frequencies.
 * @export
 * @interface FrequencyCombinationUnitResource
 */
export interface FrequencyCombinationUnitResource {
    /**
     * Frequency which the pay component would be applied.
     * @type {string}
     * @memberof FrequencyCombinationUnitResource
     */
    'payFrequency'?: string;
    /**
     * 
     * @type {PayComponentFrequencyTypeResource}
     * @memberof FrequencyCombinationUnitResource
     */
    'payComponentFrequency'?: PayComponentFrequencyTypeResource;
    /**
     * 
     * @type {Array<Link>}
     * @memberof FrequencyCombinationUnitResource
     */
    'links'?: Array<Link>;
}

