/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * These are sub intervals that are used for occurrences that are larger in duration that allow you to define when to apply the pay component. You can reference the payFrequency and occurance to determine what intervals and values applicable.
 * @export
 * @interface FrequencyIntervalsResource1
 */
export interface FrequencyIntervalsResource1 {
    /**
     * First interval
     * @type {string}
     * @memberof FrequencyIntervalsResource1
     */
    'interval1'?: string;
    /**
     * Second interval
     * @type {string}
     * @memberof FrequencyIntervalsResource1
     */
    'interval2'?: string;
}

