/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * 
 * @export
 * @interface JobSegmentsConfigResource
 */
export interface JobSegmentsConfigResource {
    /**
     * Segment Number
     * @type {number}
     * @memberof JobSegmentsConfigResource
     */
    'segmentNumber'?: number;
    /**
     * Segment Name
     * @type {string}
     * @memberof JobSegmentsConfigResource
     */
    'name'?: string;
    /**
     * Segment Length
     * @type {number}
     * @memberof JobSegmentsConfigResource
     */
    'segmentLength'?: number;
    /**
     * 
     * @type {Array<Link>}
     * @memberof JobSegmentsConfigResource
     */
    'links'?: Array<Link>;
}

