/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobSegmentsResource } from './job-segments-resource';
import { Link } from './link';

/**
 * The state representation of Jobs within a company.
 * @export
 * @interface JobResource
 */
export interface JobResource {
    /**
     * The unique identifier associated with this job.
     * @type {string}
     * @memberof JobResource
     */
    'jobId'?: string;
    /**
     * Id that you define which is used for error handling/responses.
     * @type {string}
     * @memberof JobResource
     */
    'jobCorrelationId'?: string;
    /**
     * The name of the job.
     * @type {string}
     * @memberof JobResource
     */
    'jobName'?: string;
    /**
     * The start date associated with this job.
     * @type {string}
     * @memberof JobResource
     */
    'startDate'?: string;
    /**
     * The end date associated with this job.
     * @type {string}
     * @memberof JobResource
     */
    'endDate'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof JobResource
     */
    'links'?: Array<Link>;
    /**
     * 
     * @type {JobSegmentsResource}
     * @memberof JobResource
     */
    'jobNumber'?: JobSegmentsResource;
}

