/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * The state representation of allowed worker job titles configured for the company.
 * @export
 * @interface JobTitleResource
 */
export interface JobTitleResource {
    /**
     * The name of the title.
     * @type {string}
     * @memberof JobTitleResource
     */
    'title'?: string;
    /**
     * The unique identifier associated with this job titles representation.
     * @type {string}
     * @memberof JobTitleResource
     */
    'jobTitleId'?: string;
    /**
     * Date when this job is available to be assigned to a worker.
     * @type {string}
     * @memberof JobTitleResource
     */
    'startDate'?: string;
    /**
     * Date when this job is no longer available to be assigned to a worker.
     * @type {string}
     * @memberof JobTitleResource
     */
    'endDate'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof JobTitleResource
     */
    'links'?: Array<Link>;
}

