/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Data elements of a Job Number to show the segments and number.For segmentation this can be up to 3 different segments.
 * @export
 * @interface JobSegmentsResource
 */
export interface JobSegmentsResource {
    /**
     * This is segment 1 or the number associated to the job when segmentation is not used.
     * @type {string}
     * @memberof JobSegmentsResource
     */
    'segment1'?: string;
    /**
     * This is segment 2.
     * @type {string}
     * @memberof JobSegmentsResource
     */
    'segment2'?: string;
    /**
     * This is segment 3.
     * @type {string}
     * @memberof JobSegmentsResource
     */
    'segment3'?: string;
}

