/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The workers current job/position information.
 * @export
 * @interface JobTitleResource1
 */
export interface JobTitleResource1 {
    /**
     * The name of the title that the worker is assigned to.
     * @type {string}
     * @memberof JobTitleResource1
     */
    'title'?: string;
    /**
     * Unique ID for that job within the company that the worker is assigned to.
     * @type {string}
     * @memberof JobTitleResource1
     */
    'jobTitleId'?: string;
}

