/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * The state representation of Labor Assignments within a company.
 * @export
 * @interface LaborAssignmentResource
 */
export interface LaborAssignmentResource {
    /**
     * The unique identifier associated with this labor assignment representation.
     * @type {string}
     * @memberof LaborAssignmentResource
     */
    'laborAssignmentId'?: string;
    /**
     * The name of the labor assignment.
     * @type {string}
     * @memberof LaborAssignmentResource
     */
    'name'?: string;
    /**
     * The start date associated with this labor assignment.
     * @type {string}
     * @memberof LaborAssignmentResource
     */
    'startDate'?: string;
    /**
     * The end date associated with this labor assignment.
     * @type {string}
     * @memberof LaborAssignmentResource
     */
    'endDate'?: string;
    /**
     * The organization associated with this labor assignment.
     * @type {string}
     * @memberof LaborAssignmentResource
     */
    'organizationId'?: string;
    /**
     * The position associated with this labor assignment.
     * @type {string}
     * @memberof LaborAssignmentResource
     */
    'positionId'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof LaborAssignmentResource
     */
    'links'?: Array<Link>;
    /**
     * The locations associated with this labor assignment.
     * @type {string}
     * @memberof LaborAssignmentResource
     */
    'locationId'?: string;
}

