/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The workers legal tax identification information. This data field cannot be PATCHED for ACTIVE workers.
 * @export
 * @interface LegalIdResource1
 */
export interface LegalIdResource1 {
    /**
     * A value that identifies the type of taxpayer identification number provided.   SSN: Social  Security Number - 9 digit number   , FEIN: Federal Employer Identification Number (EIN)
     * @type {string}
     * @memberof LegalIdResource1
     */
    'legalIdType'?: LegalIdResource1LegalIdTypeEnum;
    /**
     * The federal level taxpayer id number that the worker has provided
     * @type {string}
     * @memberof LegalIdResource1
     */
    'legalIdValue'?: string;
}

type LegalIdResource1LegalIdTypeEnum = 'SSN' | 'FEIN'


