/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommunicationResource } from './communication-resource';
import { Link } from './link';

/**
 * The state representation of Locations within a company.
 * @export
 * @interface LocationResource
 */
export interface LocationResource {
    /**
     * The unique identifier associated with this locations representation.
     * @type {string}
     * @memberof LocationResource
     */
    'locationId'?: string;
    /**
     * The name of the location.
     * @type {string}
     * @memberof LocationResource
     */
    'name'?: string;
    /**
     * 
     * @type {CommunicationResource}
     * @memberof LocationResource
     */
    'address'?: CommunicationResource;
    /**
     * 
     * @type {Array<Link>}
     * @memberof LocationResource
     */
    'links'?: Array<Link>;
    /**
     * The date which the location was moved into.
     * @type {string}
     * @memberof LocationResource
     */
    'movedIn'?: string;
    /**
     * The date which the location was moved out.
     * @type {string}
     * @memberof LocationResource
     */
    'movedOut'?: string;
}

