/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaginationMetadataResource } from './pagination-metadata-resource';

/**
 * 
 * @export
 * @interface MetadataResource
 */
export interface MetadataResource {
    /**
     * 
     * @type {number}
     * @memberof MetadataResource
     */
    'contentItemCount'?: number;
    /**
     * 
     * @type {PaginationMetadataResource}
     * @memberof MetadataResource
     */
    'pagination'?: PaginationMetadataResource;
}

