/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Data elements of a workers name.
 * @export
 * @interface NameResource
 */
export interface NameResource {
    /**
     * The family or last name of a worker.
     * @type {string}
     * @memberof NameResource
     */
    'familyName'?: string;
    /**
     * A subordinate given name, or initial representing that name, of a worker. <br />NOTE:  More than one char is not allowed and returns an error. <br />A full middle name can be added directly via Paychex Flex only at this time.
     * @type {string}
     * @memberof NameResource
     */
    'middleName'?: string;
    /**
     * The given or first name of a worker. For an independent contractor that is a company rather than an individual, the name of the company.
     * @type {string}
     * @memberof NameResource
     */
    'givenName'?: string;
    /**
     * The name that the worker prefers to go by; also known as a \"nickname\"
     * @type {string}
     * @memberof NameResource
     */
    'preferredName'?: string;
    /**
     * A qualifier to the name of a worker, indicating generation.
     * @type {string}
     * @memberof NameResource
     */
    'qualificationAffixCode'?: string;
    /**
     * A personal title that comes before an individual\'s name in a formal address (such as Dr., Prof., Rev., Mr.). 
     * @type {string}
     * @memberof NameResource
     */
    'titleAffixCode'?: string;
}

