/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the workers name.
 * @export
 * @interface NameResource1
 */
export interface NameResource1 {
    /**
     * The family or last name of a worker.
     * @type {string}
     * @memberof NameResource1
     */
    'familyName'?: string;
    /**
     * A subordinate given name, or initial representing that name, of a worker. <br />NOTE:  Please send in just a single character initial for middleName.  <br />If sending in more than one character the name will be truncated the first letter of the middleName. <br /> A full middle name can be entered directly in Paychex Flex only at this time.
     * @type {string}
     * @memberof NameResource1
     */
    'middleName'?: string;
    /**
     * The given or first name of a worker. For an independent contractor that is a company rather than an individual, the name of the company.
     * @type {string}
     * @memberof NameResource1
     */
    'givenName'?: string;
    /**
     * The name that the worker prefers to go by; also known as a \"nickname\"
     * @type {string}
     * @memberof NameResource1
     */
    'preferredName'?: string;
    /**
     * A qualifier to the name of a worker, indicating generation.
     * @type {string}
     * @memberof NameResource1
     */
    'qualificationAffixCode'?: string;
    /**
     * A personal title that comes before an individual\'s name in a formal address (such as Dr., Prof., Rev., Mr.). 
     * @type {string}
     * @memberof NameResource1
     */
    'titleAffixCode'?: string;
}

