/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * The state representation of Organizations within a company.
 * @export
 * @interface OrganizationResource
 */
export interface OrganizationResource {
    /**
     * The unique identifier associated with this organizations representation.
     * @type {string}
     * @memberof OrganizationResource
     */
    'organizationId'?: string;
    /**
     * The name of the organization.
     * @type {string}
     * @memberof OrganizationResource
     */
    'name'?: string;
    /**
     * The number assigned to the organization.
     * @type {string}
     * @memberof OrganizationResource
     */
    'number'?: string;
    /**
     * The level number within the organizational structures hierarchy.
     * @type {string}
     * @memberof OrganizationResource
     */
    'level'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof OrganizationResource
     */
    'links'?: Array<Link>;
}

