/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * The organization which the worker is part of.
 * @export
 * @interface OrganizationResource1
 */
export interface OrganizationResource1 {
    /**
     * The unique identifier associated with this organizations representation.
     * @type {string}
     * @memberof OrganizationResource1
     */
    'organizationId'?: string;
    /**
     * The name of the organization.
     * @type {string}
     * @memberof OrganizationResource1
     */
    'name'?: string;
    /**
     * The number assigned to the organization.
     * @type {string}
     * @memberof OrganizationResource1
     */
    'number'?: string;
    /**
     * The level number within the organizational structures hierarchy.
     * @type {string}
     * @memberof OrganizationResource1
     */
    'level'?: string;
    /**
     * 
     * @type {Array<OrganizationResource1>}
     * @memberof OrganizationResource1
     */
    'children'?: Array<OrganizationResource1>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof OrganizationResource1
     */
    'links'?: Array<Link>;
}

