/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OrganizationResource2
 */
export interface OrganizationResource2 {
    /**
     * 
     * @type {string}
     * @memberof OrganizationResource2
     */
    'organizationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResource2
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResource2
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResource2
     */
    'level'?: string;
    /**
     * 
     * @type {Array<OrganizationResource2>}
     * @memberof OrganizationResource2
     */
    'children'?: Array<OrganizationResource2>;
}

