/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaginationMetadataResource
 */
export interface PaginationMetadataResource {
    /**
     * 
     * @type {number}
     * @memberof PaginationMetadataResource
     */
    'offset'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetadataResource
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetadataResource
     */
    'itemCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetadataResource
     */
    'total'?: number;
}

