/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Informational pay components on the check.
 * @export
 * @interface PayComponentResource2
 */
export interface PayComponentResource2 {
    /**
     * Description
     * @type {string}
     * @memberof PayComponentResource2
     */
    'description'?: string;
    /**
     * The identifier of the pay component to add to the check. An overtime pay component can\'t be placed on a worker that is OT exempt.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'componentId'?: string;
    /**
     * The unique identifier associated for the pay component on this check.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'checkComponentId'?: string;
    /**
     * The name given to the pay component
     * @type {string}
     * @memberof PayComponentResource2
     */
    'name'?: string;
    /**
     * The category that this component falls into.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'classificationType'?: string;
    /**
     * The effect that the pay component will have on the check amount.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'effectOnPay'?: PayComponentResource2EffectOnPayEnum;
    /**
     * The date that the pay component is able to be applied on a check.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'startDate'?: string;
    /**
     * The date that the pay component is not available to be applied on a check moving forward.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'endDate'?: string;
    /**
     * Applies To WorkerTypes.
     * @type {Array<string>}
     * @memberof PayComponentResource2
     */
    'appliesToWorkerTypes'?: Array<PayComponentResource2AppliesToWorkerTypesEnum>;
    /**
     * This is used optionally for overriding a job when it needs to be different then the workers default. This option is only available when the client has job costing.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'jobId'?: string;
    /**
     * This is used optionally for overriding a labor assignment when it needs to be different then the workers assignment distribution. This option is only available when the client has labor assignment.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'laborAssignmentId'?: string;
    /**
     * The rate identifier for the workers compensation
     * @type {string}
     * @memberof PayComponentResource2
     */
    'payRateId'?: string;
    /**
     * The rate amount that will be applied for this component. Used in conjunction with Hours or Units.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'payRate'?: string;
    /**
     * The number of hours that will be applied for this component. Used in conjunction with rate.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'payHours'?: string;
    /**
     * The number of units that will be applied for this component. Used in conjunction with rate.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'payUnits'?: string;
    /**
     * The flat amount to be applied for this component. Not used with Rate, Hours, or Units.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'payAmount'?: string;
    /**
     * This is used optionally for memoing the payHours or payUnits so that they are informational when using a payAmount.
     * @type {boolean}
     * @memberof PayComponentResource2
     */
    'memoed'?: boolean;
    /**
     * This is used optionally for specifying a date that the pay component was generated on.
     * @type {string}
     * @memberof PayComponentResource2
     */
    'lineDate'?: string;
}

type PayComponentResource2EffectOnPayEnum = 'ADDITION' | 'ADDITION_WITH_IN_OUT' | 'EMPLOYER_INFORMATIONAL' | 'REDUCTION'
type PayComponentResource2AppliesToWorkerTypesEnum = 'EMPLOYEE' | 'CONTRACTOR' | 'INDEPENDENT_CONTRACTOR'


