/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayRateResource } from './pay-rate-resource';
import { PayStandardResource } from './pay-standard-resource';

/**
 * Worker Pay Rate  Standard
 * @export
 * @interface PayRatesStandardResource
 */
export interface PayRatesStandardResource {
    /**
     * 
     * @type {PayStandardResource}
     * @memberof PayRatesStandardResource
     */
    'payStandards'?: PayStandardResource;
    /**
     * 
     * @type {Array<PayRateResource>}
     * @memberof PayRatesStandardResource
     */
    'payRates'?: Array<PayRateResource>;
}

