/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * Worker Pay Rate
 * @export
 * @interface PayRateResource
 */
export interface PayRateResource {
    /**
     * Describes the rate for the worker.
     * @type {string}
     * @memberof PayRateResource
     */
    'description'?: string;
    /**
     * Unique identifier for this workers pay rate. **This ID will change if this is created for an IN_PROGRESS worker that is later completed within Flex**
     * @type {string}
     * @memberof PayRateResource
     */
    'rateId'?: string;
    /**
     * The date when the pay rate is going to begin.
     * @type {string}
     * @memberof PayRateResource
     */
    'startDate'?: string;
    /**
     * The number of the rate. A worker can have up to 5 different rates.
     * @type {string}
     * @memberof PayRateResource
     */
    'rateNumber'?: string;
    /**
     * Type of rate.
     * @type {string}
     * @memberof PayRateResource
     */
    'rateType'?: PayRateResourceRateTypeEnum;
    /**
     * The currency amount which this rate is applied.
     * @type {string}
     * @memberof PayRateResource
     */
    'amount'?: string;
    /**
     * Default standard hours that this rate is used with a pay frequency.
     * @type {string}
     * @memberof PayRateResource
     */
    'standardHours'?: string;
    /**
     * Default over time hours that this rate is used with a pay frequency.
     * @type {string}
     * @memberof PayRateResource
     */
    'standardOvertime'?: string;
    /**
     * If this rate is the default one to apply on the worker.
     * @type {boolean}
     * @memberof PayRateResource
     */
    'default'?: boolean;
    /**
     * The date when the pay rate becomes effective for the worker.(can be used only in POST/PATCH for an active worker)
     * @type {string}
     * @memberof PayRateResource
     */
    'effectiveDate'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof PayRateResource
     */
    'links'?: Array<Link>;
}

type PayRateResourceRateTypeEnum = 'ANNUAL_SALARY' | 'PER_PAY_PERIOD_SALARY' | 'PIECEWORK_RATE' | 'DAILY_RATE' | 'HOURLY_RATE'


