/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * The representational state of pay periods.
 * @export
 * @interface PayPeriodResource
 */
export interface PayPeriodResource {
    /**
     * The description of the Pay Period.
     * @type {string}
     * @memberof PayPeriodResource
     */
    'description'?: string;
    /**
     * The unique identifier used to identify a pay period.
     * @type {string}
     * @memberof PayPeriodResource
     */
    'payPeriodId'?: string;
    /**
     * Frequency of the payroll period.
     * @type {string}
     * @memberof PayPeriodResource
     */
    'intervalCode'?: PayPeriodResourceIntervalCodeEnum;
    /**
     * The current state of the associated pay period.
     * @type {string}
     * @memberof PayPeriodResource
     */
    'status'?: PayPeriodResourceStatusEnum;
    /**
     * The start date associated with this pay period.
     * @type {string}
     * @memberof PayPeriodResource
     */
    'startDate'?: string;
    /**
     * The end date associated with this pay period.
     * @type {string}
     * @memberof PayPeriodResource
     */
    'endDate'?: string;
    /**
     * The date by which information for the pay run must be submitted in order to be guaranteed the information is included.
     * @type {string}
     * @memberof PayPeriodResource
     */
    'submitByDate'?: string;
    /**
     * The date on which the checks associated with this pay period can be cashed.
     * @type {string}
     * @memberof PayPeriodResource
     */
    'checkDate'?: string;
    /**
     * Number of checks that are included within the pay period.
     * @type {number}
     * @memberof PayPeriodResource
     */
    'checkCount'?: number;
    /**
     * 
     * @type {Array<Link>}
     * @memberof PayPeriodResource
     */
    'links'?: Array<Link>;
}

type PayPeriodResourceIntervalCodeEnum = 'ANNUAL' | 'BI_WEEKLY' | 'MONTHLY' | 'QUARTERLY' | 'SEMI_ANNUAL' | 'SEMI_MONTHLY' | 'WEEKLY'
type PayPeriodResourceStatusEnum = 'COMPLETED' | 'COMPLETED_BY_MEC' | 'ENTRY' | 'INITIAL' | 'PROCESSING' | 'REISSUED' | 'RELEASED' | 'REVERSED'


