/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FrequencyIntervalsResource1 } from './frequency-intervals-resource1';

/**
 * Worker pay frequency
 * @export
 * @interface PayComponentFrequencyTypeResource1
 */
export interface PayComponentFrequencyTypeResource1 {
    /**
     * Currently we only support a BY_PAY_PERIOD value for the API.
     * @type {string}
     * @memberof PayComponentFrequencyTypeResource1
     */
    'applied'?: string;
    /**
     * This is how often the pay component will be applied on the pay run. The available values for this will depend on the payFrequency that a worker is paid which can be found on the worker compensations pay standards.
     * @type {string}
     * @memberof PayComponentFrequencyTypeResource1
     */
    'occurrence'?: string;
    /**
     * 
     * @type {FrequencyIntervalsResource1}
     * @memberof PayComponentFrequencyTypeResource1
     */
    'occurrenceIntervals'?: FrequencyIntervalsResource1;
    /**
     * Which check(s) within the payrun that the paycomponent will be applied to.FIRST_CHECK: The Pay Component will be applied to the first check for the worker within the pay run. This is used for a pay component that only should be applied once like a health insurance deduction.EVERY_CHECK: The Pay Component will be applied to all of the checks for the worker within the pay run. This is used for a pay component that is applied on all check like a retirement deduction.
     * @type {string}
     * @memberof PayComponentFrequencyTypeResource1
     */
    'effectedChecks'?: string;
}

