/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A pay component defined for a client
 * @export
 * @interface PayComponent
 */
export interface PayComponent {
    /**
     * 
     * @type {number}
     * @memberof PayComponent
     */
    'cltpcId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'offeringId'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayComponent
     */
    'pcId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'customName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'reportCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PayComponent
     */
    'isPaychexAdministered'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PayComponent
     */
    'deductionPriority'?: number;
    /**
     * 
     * @type {number}
     * @memberof PayComponent
     */
    'refId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'payCompName'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayComponent
     */
    'payCpntTypeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'payCpntType'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayComponent
     */
    'classTypeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'classType'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayComponent
     */
    'payFreqId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'payFreq'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayComponent
     */
    'freqTypeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'freqType'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayComponent
     */
    'firstCheckRuleId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'firstCheckRule'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PayComponent
     */
    'isBankRequired'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PayComponent
     */
    'collectArrearsOnShortfall'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayComponent
     */
    'endDate'?: string;
}

