/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FrequencyIntervalsResource } from './frequency-intervals-resource';

/**
 * Pay Component Frequency
 * @export
 * @interface PayComponentFrequencyTypeResource
 */
export interface PayComponentFrequencyTypeResource {
    /**
     * Currently we only support a BY_PAY_PERIOD value for the API.
     * @type {string}
     * @memberof PayComponentFrequencyTypeResource
     */
    'applied'?: string;
    /**
     * This is how often the to be applied on the pay run.
     * @type {string}
     * @memberof PayComponentFrequencyTypeResource
     */
    'occurrence'?: string;
    /**
     * 
     * @type {FrequencyIntervalsResource}
     * @memberof PayComponentFrequencyTypeResource
     */
    'occurrenceIntervals'?: FrequencyIntervalsResource;
}

