/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Worker Pay Standard
 * @export
 * @interface PayStandardResource
 */
export interface PayStandardResource {
    /**
     * How often a worker is paid.
     * @type {string}
     * @memberof PayStandardResource
     */
    'payFrequency'?: PayStandardResourcePayFrequencyEnum;
    /**
     * Default overtime factor that would be applied for overtime work completed.
     * @type {string}
     * @memberof PayStandardResource
     */
    'overtimeFactor'?: string;
    /**
     * Calculated amount of compensation based on rate defaults.
     * @type {string}
     * @memberof PayStandardResource
     */
    'calculatedPayPeriod'?: string;
    /**
     * Calculated amount of compensation based on calculatedPayPeriod and payFrequency.
     * @type {string}
     * @memberof PayStandardResource
     */
    'calculatedAnnualSalary'?: string;
}

type PayStandardResourcePayFrequencyEnum = 'WEEKLY' | 'BI_WEEKLY' | 'SEMI_MONTHLY' | 'MONTHLY'


