/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NameResource1 } from './name-resource1';
import { PersonCommunicationResource } from './person-communication-resource';

/**
 * The person associated with this relationship. The relationship must have either a person or entity.
 * @export
 * @interface PersonResource
 */
export interface PersonResource {
    /**
     * 
     * @type {NameResource1}
     * @memberof PersonResource
     */
    'name'?: NameResource1;
    /**
     * 
     * @type {PersonCommunicationResource}
     * @memberof PersonResource
     */
    'communication'?: PersonCommunicationResource;
}

