/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The postal communications for this contact.
 * @export
 * @interface PostalResource
 */
export interface PostalResource {
    /**
     * The ID for the workers relationship to contact.
     * @type {string}
     * @memberof PostalResource
     */
    'communicationId'?: string;
    /**
     * The street address line one. Required for street address. Required for POST contacts.
     * @type {string}
     * @memberof PostalResource
     */
    'streetLineOne'?: string;
    /**
     * The street address line two.
     * @type {string}
     * @memberof PostalResource
     */
    'streetLineTwo'?: string;
    /**
     * The postal office box. Required for PO Box with POST contacts.
     * @type {string}
     * @memberof PostalResource
     */
    'postOfficeBox'?: string;
    /**
     * The city name. Required for POST contacts.
     * @type {string}
     * @memberof PostalResource
     */
    'city'?: string;
    /**
     * The zip-code. Required for POST contacts.
     * @type {string}
     * @memberof PostalResource
     */
    'postalCode'?: string;
    /**
     * The state code (ISO 3166 subdivision code). Required for POST contacts.
     * @type {string}
     * @memberof PostalResource
     */
    'countrySubdivisionCode'?: string;
    /**
     * The country code (ISO 3166 alpha-2). Required for POST contacts.
     * @type {string}
     * @memberof PostalResource
     */
    'countryCode'?: string;
}

