/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { ProcessedCheckComponentResource } from './processed-check-component-resource';

/**
 * 
 * @export
 * @interface ProcessedCheckResource
 */
export interface ProcessedCheckResource {
    /**
     * 
     * @type {string}
     * @memberof ProcessedCheckResource
     */
    'payPeriodId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessedCheckResource
     */
    'paycheckId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessedCheckResource
     */
    'workerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessedCheckResource
     */
    'checkDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessedCheckResource
     */
    'netPay'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessedCheckResource
     */
    'checkType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessedCheckResource
     */
    'checkNumber'?: string;
    /**
     * 
     * @type {Array<ProcessedCheckComponentResource>}
     * @memberof ProcessedCheckResource
     */
    'earnings'?: Array<ProcessedCheckComponentResource>;
    /**
     * 
     * @type {Array<ProcessedCheckComponentResource>}
     * @memberof ProcessedCheckResource
     */
    'deductions'?: Array<ProcessedCheckComponentResource>;
    /**
     * 
     * @type {Array<ProcessedCheckComponentResource>}
     * @memberof ProcessedCheckResource
     */
    'informational'?: Array<ProcessedCheckComponentResource>;
    /**
     * 
     * @type {Array<ProcessedCheckComponentResource>}
     * @memberof ProcessedCheckResource
     */
    'taxes'?: Array<ProcessedCheckComponentResource>;
    /**
     * 
     * @type {string}
     * @memberof ProcessedCheckResource
     */
    'grossEarnings'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof ProcessedCheckResource
     */
    'links'?: Array<Link>;
}

