/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PurchaseResource1
 */
export interface PurchaseResource1 {
    /**
     * 
     * @type {string}
     * @memberof PurchaseResource1
     */
    'transactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseResource1
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseResource1
     */
    'count'?: string;
    /**
     * 
     * @type {number}
     * @memberof PurchaseResource1
     */
    'price'?: number;
}

