/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * 
 * @export
 * @interface PurchaseResource
 */
export interface PurchaseResource {
    /**
     * 
     * @type {string}
     * @memberof PurchaseResource
     */
    'transactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseResource
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseResource
     */
    'count'?: string;
    /**
     * 
     * @type {number}
     * @memberof PurchaseResource
     */
    'price'?: number;
    /**
     * 
     * @type {Array<Link>}
     * @memberof PurchaseResource
     */
    'links'?: Array<Link>;
}

