/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { PayComponentFrequencyTypeResource1 } from './pay-component-frequency-type-resource1';

/**
 * Worker recurring deduction
 * @export
 * @interface RecurringResource
 */
export interface RecurringResource {
    /**
     * The id of a single pay component that a workers has.
     * @type {string}
     * @memberof RecurringResource
     */
    'workerComponentId'?: string;
    /**
     * The unique identifier of the pay component. This data field cannot be PATCHED.
     * @type {string}
     * @memberof RecurringResource
     */
    'componentId'?: string;
    /**
     * Name of the pay component. This data field will be populated automatically based on componentId.
     * @type {string}
     * @memberof RecurringResource
     */
    'name'?: string;
    /**
     * The type of calculation that will be applied for the pay component .
     * @type {string}
     * @memberof RecurringResource
     */
    'calculationType'?: RecurringResourceCalculationTypeEnum;
    /**
     * This is required if you are not using a FLAT_DOLLAR_AMOUNT Calculation Type.
     * @type {string}
     * @memberof RecurringResource
     */
    'calculationBaseId'?: string;
    /**
     * This is used to specify the value that is used against the calculationType.
     * @type {number}
     * @memberof RecurringResource
     */
    'value'?: number;
    /**
     * Date which this pay component will start to be applied during the payruns. This is an optional field that default to current datetime if not provided. This cannot be backdated but can be added to start in the future.
     * @type {string}
     * @memberof RecurringResource
     */
    'startDate'?: string;
    /**
     * Date which this pay component has started for the worker.
     * @type {string}
     * @memberof RecurringResource
     */
    'effectiveDate'?: string;
    /**
     * Date which this pay component has ended for the worker.
     * @type {string}
     * @memberof RecurringResource
     */
    'endDate'?: string;
    /**
     * What the effect on pay will be (REDUCTION OR ADDITION), currently only reductions are available. This data field will be populated automatically based on componentId. This data field cannot be PATCHED
     * @type {string}
     * @memberof RecurringResource
     */
    'effectOnPay'?: string;
    /**
     * The category that this component falls into.
     * @type {string}
     * @memberof RecurringResource
     */
    'classificationType'?: string;
    /**
     * 
     * @type {PayComponentFrequencyTypeResource1}
     * @memberof RecurringResource
     */
    'frequency'?: PayComponentFrequencyTypeResource1;
    /**
     * 
     * @type {Array<Link>}
     * @memberof RecurringResource
     */
    'links'?: Array<Link>;
}

type RecurringResourceCalculationTypeEnum = 'FLAT_DOLLAR_AMOUNT:This is used for a specific dollar amount' | 'PERCENTAGE:This is used for when a Percentage will be used to calculate the amount and will need a calculationBaseId to specify what to apply against' | 'RATE_X_UNITS:This is used for apply the rate against units and will need a calculationBaseId to specify what to apply against' | 'RATE_X_HOURS:This is used for apply the rate against hours and will need a calculationBaseId to specify what to apply against.'


