/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RelationTypeResource
 */
export interface RelationTypeResource {
    /**
     * 
     * @type {string}
     * @memberof RelationTypeResource
     */
    'relationshipTypeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationTypeResource
     */
    'relationshipTypeName'?: string;
}

