/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EntityResource } from './entity-resource';
import { PersonResource } from './person-resource';
import { RelationTypeResource1 } from './relation-type-resource1';

/**
 * The relationship for this worker contract. Required for POST contacts.
 * @export
 * @interface RelationshipResource
 */
export interface RelationshipResource {
    /**
     * The ID for the workers relationship to contact.
     * @type {string}
     * @memberof RelationshipResource
     */
    'relationshipId'?: string;
    /**
     * The ID for the workers specific relation.
     * @type {string}
     * @memberof RelationshipResource
     */
    'relationWeid'?: string;
    /**
     * 
     * @type {RelationTypeResource1}
     * @memberof RelationshipResource
     */
    'relationshipType'?: RelationTypeResource1;
    /**
     * Where to indicate if the contact is selected as Primary, where true = Primary contact and false = not Primary contact.
     * @type {boolean}
     * @memberof RelationshipResource
     */
    'primary'?: boolean;
    /**
     * 
     * @type {PersonResource}
     * @memberof RelationshipResource
     */
    'person'?: PersonResource;
    /**
     * 
     * @type {EntityResource}
     * @memberof RelationshipResource
     */
    'entity'?: EntityResource;
}

