/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportResource
 */
export interface ReportResource {
    /**
     * 
     * @type {string}
     * @memberof ReportResource
     */
    'documentName'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReportResource
     */
    'documentContent'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ReportResource
     */
    'fileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportResource
     */
    'type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReportResource
     */
    'size'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReportResource
     */
    'successIndicator'?: boolean;
}

