/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The workers employment status information. This data field cannot be POSTED and PATCHED for IN_PROGRESS worker.
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * The unique identifier associated with this status representation.
     * @type {string}
     * @memberof Status
     */
    'workerStatusId'?: string;
    /**
     * The workers current status.
     * @type {string}
     * @memberof Status
     */
    'statusType'?: StatusStatusTypeEnum;
    /**
     * The detailed reason of the workers current status.
     * @type {string}
     * @memberof Status
     */
    'statusReason'?: string;
}

type StatusStatusTypeEnum = 'ACTIVE' | 'INACTIVE' | 'TERMINATED' | 'PENDING' | 'IN_PROGRESS'


