/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * The workers employment status information. This data field cannot be POSTED and PATCHED for IN_PROGRESS worker.
 * @export
 * @interface Status1
 */
export interface Status1 {
    /**
     * The unique identifier associated with this status representation.
     * @type {string}
     * @memberof Status1
     */
    'workerStatusId'?: string;
    /**
     * The workers current status.
     * @type {string}
     * @memberof Status1
     */
    'statusType'?: Status1StatusTypeEnum;
    /**
     * The detailed reason of the workers current status.
     * @type {string}
     * @memberof Status1
     */
    'statusReason'?: string;
    /**
     * Date that this status has started for the worker.
     * @type {string}
     * @memberof Status1
     */
    'effectiveDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof Status1
     */
    'order'?: number;
    /**
     * 
     * @type {Array<Link>}
     * @memberof Status1
     */
    'links'?: Array<Link>;
}

type Status1StatusTypeEnum = 'ACTIVE' | 'INACTIVE' | 'TERMINATED' | 'PENDING' | 'IN_PROGRESS'


