/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NameResource1 } from './name-resource1';

/**
 * The workers supervisor information.
 * @export
 * @interface SupervisorResource1
 */
export interface SupervisorResource1 {
    /**
     * The supervisor\'s Id
     * @type {string}
     * @memberof SupervisorResource1
     */
    'workerId'?: string;
    /**
     * 
     * @type {NameResource1}
     * @memberof SupervisorResource1
     */
    'name'?: NameResource1;
}

