/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NameResource } from './name-resource';

/**
 * The workers supervisor information.
 * @export
 * @interface SupervisorResource
 */
export interface SupervisorResource {
    /**
     * The supervisor Id
     * @type {string}
     * @memberof SupervisorResource
     */
    'workerId'?: string;
    /**
     * 
     * @type {NameResource}
     * @memberof SupervisorResource
     */
    'name'?: NameResource;
}

