/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The representational state of a workers time off.
 * @export
 * @interface TimeOffResource
 */
export interface TimeOffResource {
    /**
     * The unique ID assigned to the company policy.
     * @type {string}
     * @memberof TimeOffResource
     */
    'policyId'?: string;
    /**
     * The policy type the client has assigned at the company level
     * @type {string}
     * @memberof TimeOffResource
     */
    'type'?: string;
    /**
     * The name of the policy the client has assigned at the company level.
     * @type {string}
     * @memberof TimeOffResource
     */
    'name'?: string;
    /**
     * The current balance for this worker, for the associated policy type.
     * @type {string}
     * @memberof TimeOffResource
     */
    'balance'?: string;
    /**
     * Type of measurement type to be applied to the balance.
     * @type {string}
     * @memberof TimeOffResource
     */
    'measure'?: TimeOffResourceMeasureEnum;
}

type TimeOffResourceMeasureEnum = 'HOURS' | 'UNITS'


