/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebhookResponse
 */
export interface WebhookResponse {
    /**
     * 
     * @type {string}
     * @memberof WebhookResponse
     */
    'hookId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookResponse
     */
    'companyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookResponse
     */
    'uri'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookResponse
     */
    'authType'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookResponse
     */
    'createdDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookResponse
     */
    'active'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookResponse
     */
    'domains'?: Array<string>;
}

