/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Authentication1 } from './authentication1';
import { Link } from './link';

/**
 * This resource is for registering/unregistering webhooks.
 * @export
 * @interface WebhookRequest
 */
export interface WebhookRequest {
    /**
     * The unique identifier associated with this webhook. Not required for Posting.
     * @type {string}
     * @memberof WebhookRequest
     */
    'hookId'?: string;
    /**
     * Enter a valid URL for the webhook to receive events.
     * @type {string}
     * @memberof WebhookRequest
     */
    'uri': string;
    /**
     * ID associated with desired company that will receive the webhook notifications. NOTE: If no Company ID is provided in the POST, then all companies linked to the app will receive notifications.
     * @type {string}
     * @memberof WebhookRequest
     */
    'companyId'?: string;
    /**
     * 
     * @type {Authentication1}
     * @memberof WebhookRequest
     */
    'authentication': Authentication1;
    /**
     * List of available domains to register to. Refer to webhook documentation https://developer.paychex.com/documentation#operation/domains.
     * @type {Array<string>}
     * @memberof WebhookRequest
     */
    'domains': Array<string>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof WebhookRequest
     */
    'links'?: Array<Link>;
}

