/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';

/**
 * The state representation of allowed worker statuses configured for the company.
 * @export
 * @interface WorkerStatus
 */
export interface WorkerStatus {
    /**
     * The unique identifier associated with this status representation.
     * @type {string}
     * @memberof WorkerStatus
     */
    'workerStatusId'?: string;
    /**
     * The status category.
     * @type {string}
     * @memberof WorkerStatus
     */
    'statusType'?: string;
    /**
     * The reason of the status.
     * @type {string}
     * @memberof WorkerStatus
     */
    'statusReason'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof WorkerStatus
     */
    'links'?: Array<Link>;
}

