/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The representational state of the a worker\'s federal tax setup.
 * @export
 * @interface WorkerFederalTaxResource
 */
export interface WorkerFederalTaxResource {
    /**
     * The ID for the federal tax item.
     * @type {string}
     * @memberof WorkerFederalTaxResource
     */
    'taxId'?: string;
    /**
     * Filing status.
     * @type {string}
     * @memberof WorkerFederalTaxResource
     */
    'filingStatus'?: WorkerFederalTaxResourceFilingStatusEnum;
    /**
     * See federal W-4 instructions.
     * @type {string}
     * @memberof WorkerFederalTaxResource
     */
    'multipleJobs'?: WorkerFederalTaxResourceMultipleJobsEnum;
    /**
     * See federal W-4 instructions.
     * @type {string}
     * @memberof WorkerFederalTaxResource
     */
    'dependentsAmount'?: string;
    /**
     * See federal W-4 instructions.
     * @type {string}
     * @memberof WorkerFederalTaxResource
     */
    'otherIncome'?: string;
    /**
     * See federal W-4 instructions.
     * @type {string}
     * @memberof WorkerFederalTaxResource
     */
    'deductionsAmount'?: string;
    /**
     * Additional tax you want withheld each pay period.
     * @type {string}
     * @memberof WorkerFederalTaxResource
     */
    'extraWithholdingAmount'?: string;
    /**
     * Should federal taxes be withheld.
     * @type {string}
     * @memberof WorkerFederalTaxResource
     */
    'taxesWithheld'?: WorkerFederalTaxResourceTaxesWithheldEnum;
}

type WorkerFederalTaxResourceFilingStatusEnum = 'SINGLE_OR_MARRIED_FILING_SEPARATELY' | 'MARRIED_FILING_JOINTLY' | 'HEAD_OF_HOUSEHOLD'
type WorkerFederalTaxResourceMultipleJobsEnum = 'true' | 'false'
type WorkerFederalTaxResourceTaxesWithheldEnum = 'true = Federal taxes withheld' | 'false = Federal taxes are NOT withheld. Earnings will be reported to state and federal agencies.'


