/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommunicationResource1 } from './communication-resource1';
import { JobTitleResource1 } from './job-title-resource1';
import { LegalIdResource1 } from './legal-id-resource1';
import { Link } from './link';
import { NameResource1 } from './name-resource1';
import { OrganizationResource1 } from './organization-resource1';
import { Status1 } from './status1';
import { SupervisorResource1 } from './supervisor-resource1';

/**
 * 
 * @export
 * @interface WorkerResource1
 */
export interface WorkerResource1 {
    /**
     * The unique identifier associated with this worker representation.
     * @type {string}
     * @memberof WorkerResource1
     */
    'workerId'?: string;
    /**
     * The workers employee identification information.
     * @type {string}
     * @memberof WorkerResource1
     */
    'employeeId'?: string;
    /**
     * The type of worker. This data field cannot be PATCHED.
     * @type {string}
     * @memberof WorkerResource1
     */
    'workerType'?: WorkerResource1WorkerTypeEnum;
    /**
     * The type of employment for the worker.
     * @type {string}
     * @memberof WorkerResource1
     */
    'employmentType'?: WorkerResource1EmploymentTypeEnum;
    /**
     * The Overtime classification of the worker. This data field cannot be PATCHED for ACTIVE workers.
     * @type {string}
     * @memberof WorkerResource1
     */
    'exemptionType'?: WorkerResource1ExemptionTypeEnum;
    /**
     * The workers date of birth. It cannot be greater than today\'s date.
     * @type {string}
     * @memberof WorkerResource1
     */
    'birthDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkerResource1
     */
    'sex'?: WorkerResource1SexEnum;
    /**
     * Disclaimer:This parameter is not visible in Flex for the client. This data field cannot be PATCHED for ACTIVE workers.
     * @type {string}
     * @memberof WorkerResource1
     */
    'ethnicityCode'?: string;
    /**
     * The date which the worker was hired. It cannot be PATCHED for ACTIVE workers.
     * @type {string}
     * @memberof WorkerResource1
     */
    'hireDate'?: string;
    /**
     * The clock ID of the worker that can be an identification for other systems.
     * @type {string}
     * @memberof WorkerResource1
     */
    'clockId'?: string;
    /**
     * 
     * @type {NameResource1}
     * @memberof WorkerResource1
     */
    'name'?: NameResource1;
    /**
     * 
     * @type {LegalIdResource1}
     * @memberof WorkerResource1
     */
    'legalId'?: LegalIdResource1;
    /**
     * The workers home labor assignment. This data field cannot be POSTED or PATCHED.
     * @type {string}
     * @memberof WorkerResource1
     */
    'laborAssignmentId'?: string;
    /**
     * The workers location. This data field cannot be POSTED or PATCHED.
     * @type {string}
     * @memberof WorkerResource1
     */
    'locationId'?: string;
    /**
     * The workers home job. This data field cannot be POSTED or PATCHED.
     * @type {string}
     * @memberof WorkerResource1
     */
    'jobId'?: string;
    /**
     * 
     * @type {JobTitleResource1}
     * @memberof WorkerResource1
     */
    'job'?: JobTitleResource1;
    /**
     * 
     * @type {OrganizationResource1}
     * @memberof WorkerResource1
     */
    'organization'?: OrganizationResource1;
    /**
     * 
     * @type {SupervisorResource1}
     * @memberof WorkerResource1
     */
    'supervisor'?: SupervisorResource1;
    /**
     * 
     * @type {Status1}
     * @memberof WorkerResource1
     */
    'currentStatus'?: Status1;
    /**
     * Worker Communications. This data field cannot be updated for worker endpoint.
     * @type {Array<CommunicationResource1>}
     * @memberof WorkerResource1
     */
    'communications'?: Array<CommunicationResource1>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof WorkerResource1
     */
    'links'?: Array<Link>;
    /**
     * Id that you define which is used for error handling/responses.This data field is used while POSTING multiple IN_PROGRESS workers
     * @type {string}
     * @memberof WorkerResource1
     */
    'workerCorrelationId'?: string;
}

type WorkerResource1WorkerTypeEnum = 'EMPLOYEE' | 'CONTRACTOR' | 'INDEPENDENT_CONTRACTOR'
type WorkerResource1EmploymentTypeEnum = 'FULL_TIME' | 'PART_TIME'
type WorkerResource1ExemptionTypeEnum = 'EXEMPT' | 'NON_EXEMPT'
type WorkerResource1SexEnum = 'MALE' | 'FEMALE' | 'NOT_SPECIFIED'


