/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorMessageResource } from './error-message-resource';
import { Link } from './link';

/**
 * 
 * @export
 * @interface WorkerErrorResource
 */
export interface WorkerErrorResource {
    /**
     * 
     * @type {string}
     * @memberof WorkerErrorResource
     */
    'employeeFirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkerErrorResource
     */
    'employeeLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkerErrorResource
     */
    'employeeNumber'?: string;
    /**
     * 
     * @type {Array<ErrorMessageResource>}
     * @memberof WorkerErrorResource
     */
    'ErrorMessage'?: Array<ErrorMessageResource>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof WorkerErrorResource
     */
    'links'?: Array<Link>;
}

