/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContactTypeResource1 } from './contact-type-resource1';
import { RelationshipResource } from './relationship-resource';

/**
 * 
 * @export
 * @interface WorkerContactResource
 */
export interface WorkerContactResource {
    /**
     * The ID for the workers specific contact.
     * @type {string}
     * @memberof WorkerContactResource
     */
    'contactId'?: string;
    /**
     * 
     * @type {ContactTypeResource1}
     * @memberof WorkerContactResource
     */
    'contactType'?: ContactTypeResource1;
    /**
     * 
     * @type {RelationshipResource}
     * @memberof WorkerContactResource
     */
    'relationship'?: RelationshipResource;
}

