/*
External API



# Developer Resources
 Refer
[Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommunicationResource } from './communication-resource';
import { JobTitleResource } from './job-title-resource';
import { LegalIdResource } from './legal-id-resource';
import { NameResource } from './name-resource';
import { OrganizationResource } from './organization-resource';
import { Status } from './status';
import { SupervisorResource } from './supervisor-resource';

/**
 * 
 * @export
 * @interface WorkerResource
 */
export interface WorkerResource {
    /**
     * The unique identifier associated with this worker representation.
     * @type {string}
     * @memberof WorkerResource
     */
    'workerId'?: string;
    /**
     * The workers employee identification information.
     * @type {string}
     * @memberof WorkerResource
     */
    'employeeId'?: string;
    /**
     * The type of worker. This data field cannot be PATCHED.
     * @type {string}
     * @memberof WorkerResource
     */
    'workerType'?: WorkerResourceWorkerTypeEnum;
    /**
     * The type of employment for the worker.
     * @type {string}
     * @memberof WorkerResource
     */
    'employmentType'?: WorkerResourceEmploymentTypeEnum;
    /**
     * The Overtime classification of the worker.This data field cannot be PATCHED for ACTIVE workers.
     * @type {string}
     * @memberof WorkerResource
     */
    'exemptionType'?: WorkerResourceExemptionTypeEnum;
    /**
     * The workers date of birth. It cannot be greater than today\'s date.
     * @type {string}
     * @memberof WorkerResource
     */
    'birthDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkerResource
     */
    'sex'?: WorkerResourceSexEnum;
    /**
     * Disclaimer:This parameter is not visible in Flex for the client. This data field cannot be PATCHED for ACTIVE workers.
     * @type {string}
     * @memberof WorkerResource
     */
    'ethnicityCode'?: WorkerResourceEthnicityCodeEnum;
    /**
     * The date which the worker was hired. It cannot be PATCHED for ACTIVE workers.
     * @type {string}
     * @memberof WorkerResource
     */
    'hireDate'?: string;
    /**
     * The clock ID of the worker that can be an identification for other systems.
     * @type {string}
     * @memberof WorkerResource
     */
    'clockId'?: string;
    /**
     * 
     * @type {NameResource}
     * @memberof WorkerResource
     */
    'name'?: NameResource;
    /**
     * 
     * @type {LegalIdResource}
     * @memberof WorkerResource
     */
    'legalId'?: LegalIdResource;
    /**
     * The workers home labor assignment. This data field cannot be POSTED or PATCHED
     * @type {string}
     * @memberof WorkerResource
     */
    'laborAssignmentId'?: string;
    /**
     * The workers home job. This data field cannot be POSTED or PATCHED.
     * @type {string}
     * @memberof WorkerResource
     */
    'jobId'?: string;
    /**
     * The workers location. This data field cannot be POSTED or PATCHED.
     * @type {string}
     * @memberof WorkerResource
     */
    'locationId'?: string;
    /**
     * 
     * @type {JobTitleResource}
     * @memberof WorkerResource
     */
    'job'?: JobTitleResource;
    /**
     * 
     * @type {OrganizationResource}
     * @memberof WorkerResource
     */
    'organization'?: OrganizationResource;
    /**
     * 
     * @type {SupervisorResource}
     * @memberof WorkerResource
     */
    'supervisor'?: SupervisorResource;
    /**
     * 
     * @type {Status}
     * @memberof WorkerResource
     */
    'currentStatus'?: Status;
    /**
     * Worker Communications. This data field cannot be updated for worker endpoint.
     * @type {Array<CommunicationResource>}
     * @memberof WorkerResource
     */
    'communications'?: Array<CommunicationResource>;
    /**
     * Id that you define which is used for error handling/responses.This data field is used while POSTING multiple IN_PROGRESS workers
     * @type {string}
     * @memberof WorkerResource
     */
    'workerCorrelationId'?: string;
}

type WorkerResourceWorkerTypeEnum = 'EMPLOYEE' | 'CONTRACTOR' | 'INDEPENDENT_CONTRACTOR'
type WorkerResourceEmploymentTypeEnum = 'FULL_TIME' | 'PART_TIME'
type WorkerResourceExemptionTypeEnum = 'EXEMPT' | 'NON_EXEMPT'
type WorkerResourceSexEnum = 'MALE' | 'FEMALE' | 'NOT_SPECIFIED'
type WorkerResourceEthnicityCodeEnum = '(blank)' | 'HISPANIC_OR_LATINO' | 'WHITE_NOT_OF_HISPANIC_ORIGIN' | 'BLACK_OR_AFRICAN_AMERICAN' | 'NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLAND' | 'ASIAN' | 'AMERICAN_INDIAN_OR_ALASKAN_NATIVE' | 'TWO_OR_MORE_RACES' | 'Prefer not to answer'


